version: '3.4'

networks: 
  bilapi-network:
    driver: bridge

services:
  db:
    container_name: sql-server-db
    image: "mcr.microsoft.com/mssql/server:2019-CU1-ubuntu-16.04"
    environment:
      SA_PASSWORD: "P@assWord1054"
      ACCEPT_EULA: "Y"
      MSSQL_AGENT_ENABLED: "true"      
    ports:
      - "5434:1433" 
    networks:
      - bilapi-network
    restart: always   
  bil-api:
    container_name: bil-api-container
    build:
      context: ../
      dockerfile: BIL.API/Dockerfile
    ports:
      - "8080:80"
    networks:
      - bilapi-network
    depends_on:
      - db
