version: '3.4'

services:
  bil-api:
    image: ${DOCKER_REGISTRY-}bilapi
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - db
    networks:
      - bilapi-network
  db:
    image: postgres:12.2
    container_name: db_pg
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: abcd1234!
    networks:
      - bilapi-network
  pgadmin:
    image: dpage/pgadmin4:4.18
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "souza1981@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2020!"
    ports:
      - "16543:80"
    depends_on:
      - db
    networks:
      - bilapi-network
  bil-redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass Redis2020!
    hostname: redis
    ports:
      - 6379:6379
    networks:
      - bilapi-network
  bil-redis-manager:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
      - REDIS_PASSWORD=Redis2020! 
    ports:
      - "8081:8081"
    networks:
      - bilapi-network
networks:
  bilapi-network:
    driver: bridge