version: '3.4'

services:
  bil-api:
    image: ${DOCKER_REGISTRY-}bilapi
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - db
    networks:
      - bilapi-network
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: abcd1234!
    volumes:
      - /home/souza/source/volumes/postgres
    networks:
      - bilapi-network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "souza1981@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2020!"
    ports:
      - "16543:80"
    depends_on:
      - db
    networks:
      - bilapi-network
networks:
  bilapi-network:
    driver: bridge
